# Default values for docker-hub-rate-limit-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
    # Log level of the exporter
    verbosity: 1
    dockerhub:
        username: ""
        password: ""

deployment:
    enabled: true

daemonset:
    enabled: false

image:
    repository: viadee/docker-hub-rate-limit-exporter
    tag: ""
    pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceMonitor:
    enabled: false
    additionalLabels: {}
    namespace: ""

    jobLabel: ""

    scheme: http
    bearerTokenFile: ""
    tlsConfig: {}

    ## proxyUrl: URL of a proxy that should be used for scraping.
    ##
    proxyUrl: ""

    ## Override serviceMonitor selector
    ##
    selectorOverride: {}

    relabelings: []
    metricRelabelings: []
    interval: ""
    scrapeTimeout: 10s

serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
    imagePullSecrets: []

podSecurityContext: {}
    # fsGroup: 65534
    # runAsGroup: 65534
    # runAsNonRoot: true
    # runAsUser: 65534

securityContext: {}
  # capabilities:
  #   add:
  #   - SYS_TIME

service:
    type: ClusterIP
    port: 9100
    targetPort: 9100
    portName: metrics
    annotations: {}
    # nodePort: 

livenessProbeTimeoutSeconds: 5

readinessProbeTimeoutSeconds: 5

resources:
    limits:
        cpu: 200m
        memory: 96Mi
    requests:
        cpu: 50m
        memory: 64Mi

nodeSelector: {}

tolerations: []

priorityClassName: ""

affinity: {}

podAnnotations: [] 

# Only relevant for `deployment.enabled: true`
replicaCount: 1

# Only relevant for `daemonset.enabled: true`
updateStrategy: ""

# hostNetwork: false
# hostPID: false
